sayaw_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='reservation_App'
urlpatterns = [
  
    path('',views.mainpage, name='mainpage'),
    path('Add_new_guest/',views.add_guest ,name="add_guest"),
    path('Track_guest_records/', views.track_records, name="track_records"),
    path('Sayaw_rooms', views.view_rooms, name="rooms"),
    path('create_account/',views.create_account, name='create_account'),
    path('add_new_records/',views.add_new_records, name='add_new_records'),
    path('login-proces-authentication', views.login_process, name="login_process"),
    path('logout/', views.logout, name='logout'),
    path('admin_dashboard/',views.admin_dashboard,name='admin_dashboard'),
    path('manage_Establishment/',views.manage_establisment_view,name='manage_establishment'),
    path('add_room/',views.add_room,name='add_room'),
    path('add_cottage/', views.add_cottage, name='add_cottage'),
    path('view_bookings/',views.view_bookings,name='view_bookings'),
    path('reservation_form/<int:id>',views.room_booking_view, name='room_booking_view'),
    path('cottage_reservationform/<int:id>',views.cottage_booking_view, name="cottage_booking"),
    path('processing_room_booking',views.room_booking_process, name="room_booking_process"),
    path('code_verification',views.transaction_code_checking, name='code_verification'),
    path('view_records/<int:id>',views.view_guest_records, name="view_records"),
    path('Reservation_Payment',views.pay, name='send_payment'),
    path('Payments_viewing/',views.payments_viewing, name="payments_viewing"),
    path('view_payment_proof/<int:id>',views.view_proof,name="view_payment_proof"),
    path('turn-paid',views.turn_paid, name='turn_paid'),
    path('Delete-record/<int:id>',views.delete_record, name='delete_record'),
    path('update-views/<int:id>', views.update_views ,name="update_view"),
    path('update-records/<int:id>', views.update_record, name="update_records"),
    path('cottage-booking-process/', views.cottage_booking_process , name="cottage_booking_process"),
    path('view-guest-records', views.guest_list ,name="guest_list"),
    path('confirmation/', views.confirmation, name="confirmation"),
    path('sayaw-cottage/<int:id>',views.view_sayaw_cottage, name="view_sayaw_cottage"),
    path('sayaw-rooms/<int:id>',views.view_photos, name='view_photos'),
    path('load-data', views.data_loading, name="data-loading"),
    path('chat-box,', views.chat, name="chat"),
    # path('request-to-cancel', views.cancel_booking, name="cancel_booking"),
    path('cancel-booking-list', views.change_schedule , name="change_schedule"),
    path('cancellation-approval/', views.approve_cancellation, name="approve_cancellation"),
    path('add-nationality/', views.add_nationality, name="add-nationality"),
    path('refresher', views.refresher, name='refresher'),
    path('remove-services', views.remove_services , name="remove-services"),
    path('update-services/', views.update_services, name='update-services'),
    path('payment-approval-process/<int:id>', views.payment_effective, name="payment-effective"),
    path('update-bill/', views.down_payment, name='update-bill'),
    path('redirect-to-payments-viewing', views.goto_paidlist, name='goto_paidlist'),
    path('Feedback/<int:id>',views.feedback, name="send-feedback"),
    path('sending-message/', views.feedback_process, name="send-now"),
    path('phone-number-saving/', views.insert_number, name="insert"),
    path('Feedback-sent', views.clear_feedback, name="clear_feedback"),
    path('manage-account/', views.manage_account, name="manage_account"),
    path('set-availlable', views.reset, name="reset"),
    path('updating/', views.updating, name="updating"),
    path('code-tracking-process/', views.forgot_code, name="track-code"),
    path('collections', views.information_dashboard, name="information_dashboard"),
    path('guest-record-status-booking/',views.guest_dashboard, name="guest-dashboard"),
    path('change-Schedule/<int:id>',views.changeSchedule, name="changeschedule"),
    path('greet', views.greetingpage, name="greeting"),
    path('approve-change-schedule-view/', views.approve_change_schedule_view, name='approve_change_schedule_view'),
    path('change-schedule-process', views.change_schedule_process, name="change_schedule_process"),
    
    path('export-to-word/', views.export_to_word, name="export_to_word"),
   
    # path('Developer-security/', views.security, name="testing")
    
   
     
   
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sayaw_web_app/urls.py
from django.contrib import admin
from django.urls import path,include
# from django.conf import settings
# from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('sayaw_app.urls')),
    # url(r'^media/(P<path>).*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    # url(r'^media/(P<path>).*)$', serve,{'document_root': settings.STATIC_ROOT}),

 


]

sayaw_app/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from .models import CustomUser


class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)
    staff = forms.BooleanField(label='Staff', required=False, initial=False, widget=forms.CheckboxInput)
    superadmin = forms.BooleanField(label='Super Admin', required=False, initial=False, widget=forms.CheckboxInput)



class loginForm(AuthenticationForm):
    pass 

sayaw_app/views.py

from django.shortcuts import render,redirect,get_object_or_404,HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from .models import CustomUser,rooms,cottages,booking,paid,Guest_list,nationality,information,message_storage_1,message_storage_2,message_storage_3,gcash,paymaya,change_schedule
from .forms import RegistrationForm,loginForm
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse
from django.utils import timezone
from django.http import HttpResponse
from django.db.models import Q,Sum
import random, string
from django.http import Http404
from django.contrib import messages
from docx import Document
from django.http import HttpResponse
from io import BytesIO

def sample():
    print("sample")

def mainpage(request):
  
     return render(request,'pages/mainpage.html')


def logout_view(request):
     logout(request)
     return redirect('login') 
  
def login_process(request):
     form = loginForm()
     if request.method == "POST":
         form = loginForm(request, request.POST)
         if form.is_valid():
             username = form.cleaned_data['username']
             password = form.cleaned_data['password']
             user = authenticate(request, username=username, password=password)
             if user is not None:
                 login(request, user)
                 return redirect(reverse('reservation_App:admin_dashboard'))
             else:
                 return render(request, 'user/login.html', {"form": form,'err':'Invalid Account'})
   
     return render(request, 'pages/login.html', {"form": form})


 
     
    


                


def add_new_records(request):
     return render(request,'pages/add_new_records.html')

@login_required(login_url='reservation_App:login_process')
def admin_dashboard(request):
     user=request.user
     return render(request,'dashboard.html',{"user":user})
          


def create_account(request):
     form = RegistrationForm(request.POST)
     if request.method == "POST":
         if form.is_valid():
             username = form.cleaned_data['username']
             password = form.cleaned_data['password']
             confirm_password = form.cleaned_data['confirm_password']
             is_superadmin=form.cleaned_data['superadmin']
            
             if password == confirm_password:
                 user = CustomUser.objects.create_user(
                     username=username,
                     password=password,
                     staff=not is_superadmin, 
                     superadmin=is_superadmin
                 )
                 login(request, user)
                 return render(request,'pages/create_account.html',{'msg':'Account created successfully!'})
             else:
                 form = RegistrationForm()
                 return render(request, 'pages/create_account.html', {"form": form})

     return render(request, 'pages/create_account.html', {'form': form})


def manage_establisment_view(request):
     remove=False
     add=False
     update=False
     establishment=False
     data_load=False
     phone_number=False
     if 'remove' in request.POST:
         remove=True
     if 'add' in request.POST:
         add=True
     if 'update' in request.POST:
         update=True
     if 'establishment' in request.POST:
         establishment=True
     if 'data_load' in request.POST:
         data_load=True
     if 'phone_number' in request.POST:
         phone_number=True
     context={'remove':remove,'add':add,'update':update,'establishment':establishment,'data_load':data_load,'phone_number':phone_number}
     return render(request,'pages/manage_Establishment.html',context)

def add_room(request):
     if request.method=="POST":
         is_availlable='True'
         gate_number=request.POST.get('gate_number')
         room_number=request.POST.get('room_number')
         room_price=request.POST.get('room_price')
         photo1=request.FILES.get('p1')
         photo2=request.FILES.get('p2')
         photo3=request.FILES.get('p3')
         photo4=request.FILES.get('p4')
         description=request.POST.get('description')
         room_success_message="New room added succesfully"
         add_photo=rooms(is_availlable=is_availlable,
                         gate_number=gate_number,
                         room_number=room_number,
                         room_price=room_price,
                         front_view=photo1,
                         inside_view1=photo2,
                         inside_view2=photo3,
                         inside_view3=photo4,
                         room_description=description)
         add_photo.save()
     return render(request,'pages/manage_Establishment.html',{'room_success_message':room_success_message})

def add_cottage(request):
     if request.method=="POST":
         is_availlable='True'
         gate_number=request.POST.get('gate_number')
         cottage_number=request.POST.get('cottage_number')
         cottage_price=request.POST.get('cottage_price')
         photo1=request.FILES.get('p1')
         photo2=request.FILES.get('p2')
         photo3=request.FILES.get('p3')
         photo4=request.FILES.get('p4')
         description=request.POST.get('description')
         cottage_success_message="New cottage added succesfully"
         add_photo=cottages(is_availlable=is_availlable,
                            gate_number=gate_number,
                            cottage_number=cottage_number,
                            cottage_price=cottage_price,
                            front_view=photo1,
                            inside_view1=photo2,
                            inside_view2=photo3,
                            inside_view3=photo4,
                            cottage_description=description)
         add_photo.save()
     return render(request,'pages/manage_Establishment.html',{'cottage_success_message':cottage_success_message})



def view_bookings(request):
     records=booking.objects.all()
     if request.method=="GET":
         inputValue=request.GET.get('input_value','')
         related_records=booking.objects.filter(guest_Lastname__icontains=inputValue)
         return render(request,'pages/view_bookings.html',{'query':related_records,'input':inputValue})
     return render(request,'pages/view_bookings.html',{'records':records})

def view_photos(request,id):
     room_view=get_object_or_404(rooms,id=id)

     return render(request,'pages/view_sayaw_rooms.html',{'room_view':room_view})

def view_sayaw_cottage(request,id):
     cottage=get_object_or_404(cottages,id=id)
     return render(request,'pages/view_sayaw_cottage.html',{'cottage':cottage})


    

def room_booking_view(request,id):
     cottage=cottages.objects.all()
     current_date = timezone.now()
     room=get_object_or_404(rooms,id=id)
     return render(request,'pages/reservation_form.html',{'room':room,'cottages':cottage})



    
def cottage_booking_view(request,id):
     room=rooms.objects.all()
     cottage=get_object_or_404(cottages,id=id)  
     return render(request,'pages/cottage_reservationform.html',{'cottage':cottage,'rooms':room})


def cottage_booking_process(request):
       room_price = 0
       error_msg=""
       success_msg="Thank you for visting sayaw resort"
       current_date = timezone.now()
       date_Reserved = current_date.strftime("%Y-%m-%d")
       current_time = timezone.localtime(timezone.now()).time()
       time_Reserved = current_time.strftime('%H:%M:%S')
       entrance_Fee=40
     
       if request.method=='POST':
       
         length=6
         characters = string.ascii_letters + string.digits
         transaction_code=''.join(random.choice(characters) for i in range(length))
        
         firstName=request.POST.get('firstname').capitalize()
         lastName=request.POST.get('lastname').capitalize()
         address=request.POST.get('address').capitalize()
         guest_No=request.POST.get('guest_no')
      
         cottage_price=request.POST.get('cottage_price')
         room=request.POST.get('room')
         cottage=request.POST.get('cottage')
         gate_No=request.POST.get('gate_no')
         date_In=request.POST.get('date_in')
         date_Out=request.POST.get('date_out')
         duration=request.POST.get('duration')
         time_In=request.POST.get('time_in')
         time_Out=request.POST.get('time_out')
         payment_method=request.POST.get('payment_method')
         cottage_price=int(cottage_price)


        # Get form data and capitalize names and address
    
        
         if cottage != '':
             cottage=int(cottage)
             reserve=get_object_or_404(cottages, cottage_number=cottage)
             reserve.is_availlable=False
             reserve.save()
         else:
             pass

         if room == '':
             room=0
         else:
             room=int(room)
         if guest_No !='':
             guest_No=int(guest_No)
         else:
             guest_No=0
      

        
         if room == '10':
             if guest_No > 10 and guest_No < 15:
                     room_price = 7000
             elif guest_No > 15 :
                  room_price = 10000
         else:       
             try:
                 room=int(room)
                 reserved=get_object_or_404(rooms,room_number=room)
                 room_price=reserved.room_price
                 reserved.is_availlable=False
                 reserved.save()
             except:
                     room_price=0
               
      
            
    
        
         if duration!=0 :
             cottage_price=int(cottage_price)*int(duration)
        

sayaw_app/templates/dashboard.html

{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Admin Dashboard  {% block title %}{% endblock  %}</title>
   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/dashboard2.css' %}">
</head>


<body>
    <center><h1 id="msg" style="display:none; color:red;">This website is protected and maintained by developer! Please refrain from unauthorize access !!! </h1></center>
    <center><img id="lock" style="display:none;" src="/static/images/lock1.png" alt="" width="500" height="500"></center>
    <div class="title"  id="title">

    <header>
        <center><h1 class="header-text">Admin Dashboard</h1></center>
    </header>

    </div>
    
   {% comment %} <input class="search" type="search" placeholder="Search"><i class="fa-solid fa-magnifying-glass-location" style=" margin-left:3px;font-size:25px;color:whitesmoke;"></i>  {% endcomment %}
    
     <div class="main-container" id="main-container">

        <aside>
            
            <div class="sidebar" id="sidebar">
                
              <br>
               
                <section id="add-tourist">
                    <i class="fas fa-user-plus fa-lg" style="color:white;"></i> <a href="{% url "reservation_App:add_guest" %}">Add Guest</a>
                </section>
                <br>
               
                <section>
                    <i style="color:white;" class="fas fa-code fa-lg"></i> <a href="{% url "reservation_App:track_records" %}">Track Reference code</a>
                </section>
                <br>
                    <section>
                      
                        <i class="fa-solid fa-arrow-rotate-left fa-lg" style="color:white;"></i>  <a href="">Change Schedule</a>
                    </section>

             
                <br>
                <section>
                    <i class="fa-regular fa-address-book fa-xl" style="color:white;" ></i> <a href="{% url "reservation_App:view_bookings" %}">View Bookings</a>
                </section><br>
                <section>
                    <i class="fa-solid fa-money-bill fa-xl" style="color:white;"></i> <a  href="{% url "reservation_App:payments_viewing" %}">Down Payments</a>
                </section>
                <br>
                <section>
                    <i class="fa-solid fa-house-user fa-xl" style="color:white;"></i> <a href="{% url "reservation_App:manage_establishment" %}">Manage operations</a>
                </section>
                <br>
                <section>
                    <i class="fa-regular fa-rectangle-list fa-xl" style="color:white;" ></i>   <a href="{% url "reservation_App:guest_list" %}">Montly report</a>
                </section>
                <br>
                {% if user.is_superuser %}
                <section>
                    <i style="color:white;" class="fa-solid fa-gear fa-xl"></i>  <a href="{% url "reservation_App:manage_account" %}">Manage Account</a>
                </section>
                <br>
                <section>
                    <i class="fa-solid fa-coins fa-xl" style="color:white;" ></i> <a href="{% url "reservation_App:information_dashboard" %}">Collections</a>
                </section>
                {% endif %}
                
            </div>

        </aside>

   
    <div class="main-content">
       
        <form action="" method="POST" id="myform" >
            {% csrf_token %}
            <input type="hidden" id="text" value="{{user.username}}" name="user" onchange="this.form.submit()">
            <button  type="submit" id="button-click" style="visibility:hidden; width:100%;background-color:blue;">Test</button>
    
        </form>
{% block payment_viewing %}{% endblock  %}
{% block view_records %}{% endblock  %}
 {% block content %}{% endblock  %}
 {% block view_proof %}{% endblock view_proof %}
 {% block specific_guest_records %}{% endblock  %}
 {% block delete_records %}{% endblock  %}
 {% block update_records %}{% endblock  %}
 {% block add_guest %}{% endblock  %}
 {% block track_records %}{% endblock  %}
 {% block guest_list %}{% endblock  %}
 {% block cancel_bookings %}{% endblock  %}
 {% block payment_effective %}{% endblock  %}
 {% block feedback %}{% endblock  %}
 {% block manage_account %}{% endblock  %}
 {% block create_account %}{% endblock  %}
 {% block info_dashboard %}{% endblock  %}
    </div>
    
<br><br>


</div>
<div>
 
</div>

<script src="{% static 'js/admin_dashboard3.js'%}"></script>
</body>


</html>