sayaw_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='reservation_App'
urlpatterns = [
  
    path('',views.mainpage, name='mainpage'),
    path('Add_new_guest/',views.add_guest ,name="add_guest"),
    path('Track_guest_records/', views.track_records, name="track_records"),
    path('Sayaw_rooms', views.view_rooms, name="rooms"),
    path('create_account/',views.create_account, name='create_account'),
    path('add_new_records/',views.add_new_records, name='add_new_records'),
    path('login-proces-authentication', views.login_process, name="login_process"),
    path('logout/', views.logout, name='logout'),
    path('admin_dashboard/',views.admin_dashboard,name='admin_dashboard'),
    path('manage_Establishment/',views.manage_establisment_view,name='manage_establishment'),
    path('add_room/',views.add_room,name='add_room'),
    path('add_cottage/', views.add_cottage, name='add_cottage'),
    path('view_bookings/',views.view_bookings,name='view_bookings'),
    path('reservation_form/<int:id>',views.room_booking_view, name='room_booking_view'),
    path('cottage_reservationform/<int:id>',views.cottage_booking_view, name="cottage_booking"),
    path('processing_room_booking',views.room_booking_process, name="room_booking_process"),
    path('code_verification',views.transaction_code_checking, name='code_verification'),
    path('view_records/<int:id>',views.view_guest_records, name="view_records"),
    path('Reservation_Payment',views.pay, name='send_payment'),
    path('Payments_viewing/',views.payments_viewing, name="payments_viewing"),
    path('view_payment_proof/<int:id>',views.view_proof,name="view_payment_proof"),
    path('turn-paid',views.turn_paid, name='turn_paid'),
    path('Delete-record/<int:id>',views.delete_record, name='delete_record'),
    path('update-views/<int:id>', views.update_views ,name="update_view"),
    path('update-records/<int:id>', views.update_record, name="update_records"),
    path('cottage-booking-process/', views.cottage_booking_process , name="cottage_booking_process"),
    path('view-guest-records', views.guest_list ,name="guest_list"),
    path('confirmation/', views.confirmation, name="confirmation"),
    path('sayaw-cottage/<int:id>',views.view_sayaw_cottage, name="view_sayaw_cottage"),
    path('sayaw-rooms/<int:id>',views.view_photos, name='view_photos'),
    path('load-data', views.data_loading, name="data-loading"),
    path('chat-box,', views.chat, name="chat"),
    # path('request-to-cancel', views.cancel_booking, name="cancel_booking"),
    path('cancel-booking-list', views.change_schedule , name="change_schedule"),
    path('cancellation-approval/', views.approve_cancellation, name="approve_cancellation"),
    path('add-nationality/', views.add_nationality, name="add-nationality"),
    path('refresher', views.refresher, name='refresher'),
    path('remove-services', views.remove_services , name="remove-services"),
    path('update-services/', views.update_services, name='update-services'),
    path('payment-approval-process/<int:id>', views.payment_effective, name="payment-effective"),
    path('update-bill/', views.down_payment, name='update-bill'),
    path('redirect-to-payments-viewing', views.goto_paidlist, name='goto_paidlist'),
    path('Feedback/<int:id>',views.feedback, name="send-feedback"),
    path('sending-message/', views.feedback_process, name="send-now"),
    path('phone-number-saving/', views.insert_number, name="insert"),
    path('Feedback-sent', views.clear_feedback, name="clear_feedback"),
    path('manage-account/', views.manage_account, name="manage_account"),
    path('set-availlable', views.reset, name="reset"),
    path('updating/', views.updating, name="updating"),
    path('code-tracking-process/', views.forgot_code, name="track-code"),
    path('collections', views.information_dashboard, name="information_dashboard"),
    path('guest-record-status-booking/',views.guest_dashboard, name="guest-dashboard"),
    path('change-Schedule/<int:id>',views.changeSchedule, name="changeschedule"),
    path('greet', views.greetingpage, name="greeting"),
    path('approve-change-schedule-view/', views.approve_change_schedule_view, name='approve_change_schedule_view'),
    path('change-schedule-process', views.change_schedule_process, name="change_schedule_process"),
    
    path('export-to-word/', views.export_to_word, name="export_to_word"),
   
    # path('Developer-security/', views.security, name="testing")
    
   
     
   
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sayaw_web_app/urls.py
from django.contrib import admin
from django.urls import path,include
# from django.conf import settings
# from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('sayaw_app.urls')),
    # url(r'^media/(P<path>).*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    # url(r'^media/(P<path>).*)$', serve,{'document_root': settings.STATIC_ROOT}),

 


]

sayaw_app/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from .models import CustomUser


class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)
    staff = forms.BooleanField(label='Staff', required=False, initial=False, widget=forms.CheckboxInput)
    superadmin = forms.BooleanField(label='Super Admin', required=False, initial=False, widget=forms.CheckboxInput)



class loginForm(AuthenticationForm):
    pass 

sayaw_app/views.py

from django.shortcuts import render,redirect,get_object_or_404,HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from .models import CustomUser,rooms,cottages,booking,paid,Guest_list,nationality,information,message_storage_1,message_storage_2,message_storage_3,gcash,paymaya,change_schedule
from .forms import RegistrationForm,loginForm
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse
from django.utils import timezone
from django.http import HttpResponse
from django.db.models import Q,Sum
import random, string
from django.http import Http404
from django.contrib import messages
from docx import Document
from django.http import HttpResponse
from io import BytesIO

def sample():
    print("sample")

def mainpage(request):
  
     return render(request,'pages/mainpage.html')


def logout_view(request):
     logout(request)
     return redirect('login') 
  
def login_process(request):
     form = loginForm()
     if request.method == "POST":
         form = loginForm(request, request.POST)
         if form.is_valid():
             username = form.cleaned_data['username']
             password = form.cleaned_data['password']
             user = authenticate(request, username=username, password=password)
             if user is not None:
                 login(request, user)
                 return redirect(reverse('reservation_App:admin_dashboard'))
             else:
                 return render(request, 'user/login.html', {"form": form,'err':'Invalid Account'})
   
     return render(request, 'pages/login.html', {"form": form})


 
     
    


                


def add_new_records(request):
     return render(request,'pages/add_new_records.html')

@login_required(login_url='reservation_App:login_process')
def admin_dashboard(request):
     user=request.user
     return render(request,'dashboard.html',{"user":user})
          


def create_account(request):
     form = RegistrationForm(request.POST)
     if request.method == "POST":
         if form.is_valid():
             username = form.cleaned_data['username']
             password = form.cleaned_data['password']
             confirm_password = form.cleaned_data['confirm_password']
             is_superadmin=form.cleaned_data['superadmin']
            
             if password == confirm_password:
                 user = CustomUser.objects.create_user(
                     username=username,
                     password=password,
                     staff=not is_superadmin, 
                     superadmin=is_superadmin
                 )
                 login(request, user)
                 return render(request,'pages/create_account.html',{'msg':'Account created successfully!'})
             else:
                 form = RegistrationForm()
                 return render(request, 'pages/create_account.html', {"form": form})

     return render(request, 'pages/create_account.html', {'form': form})


def manage_establisment_view(request):
     remove=False
     add=False
     update=False
     establishment=False
     data_load=False
     phone_number=False
     if 'remove' in request.POST:
         remove=True
     if 'add' in request.POST:
         add=True
     if 'update' in request.POST:
         update=True
     if 'establishment' in request.POST:
         establishment=True
     if 'data_load' in request.POST:
         data_load=True
     if 'phone_number' in request.POST:
         phone_number=True
     context={'remove':remove,'add':add,'update':update,'establishment':establishment,'data_load':data_load,'phone_number':phone_number}
     return render(request,'pages/manage_Establishment.html',context)

def add_room(request):
     if request.method=="POST":
         is_availlable='True'
         gate_number=request.POST.get('gate_number')
         room_number=request.POST.get('room_number')
         room_price=request.POST.get('room_price')
         photo1=request.FILES.get('p1')
         photo2=request.FILES.get('p2')
         photo3=request.FILES.get('p3')
         photo4=request.FILES.get('p4')
         description=request.POST.get('description')
         room_success_message="New room added succesfully"
         add_photo=rooms(is_availlable=is_availlable,
                         gate_number=gate_number,
                         room_number=room_number,
                         room_price=room_price,
                         front_view=photo1,
                         inside_view1=photo2,
                         inside_view2=photo3,
                         inside_view3=photo4,
                         room_description=description)
         add_photo.save()
     return render(request,'pages/manage_Establishment.html',{'room_success_message':room_success_message})

def add_cottage(request):
     if request.method=="POST":
         is_availlable='True'
         gate_number=request.POST.get('gate_number')
         cottage_number=request.POST.get('cottage_number')
         cottage_price=request.POST.get('cottage_price')
         photo1=request.FILES.get('p1')
         photo2=request.FILES.get('p2')
         photo3=request.FILES.get('p3')
         photo4=request.FILES.get('p4')
         description=request.POST.get('description')
         cottage_success_message="New cottage added succesfully"
         add_photo=cottages(is_availlable=is_availlable,
                            gate_number=gate_number,
                            cottage_number=cottage_number,
                            cottage_price=cottage_price,
                            front_view=photo1,
                            inside_view1=photo2,
                            inside_view2=photo3,
                            inside_view3=photo4,
                            cottage_description=description)
         add_photo.save()
     return render(request,'pages/manage_Establishment.html',{'cottage_success_message':cottage_success_message})



def view_bookings(request):
     records=booking.objects.all()
     if request.method=="GET":
         inputValue=request.GET.get('input_value','')
         related_records=booking.objects.filter(guest_Lastname__icontains=inputValue)
         return render(request,'pages/view_bookings.html',{'query':related_records,'input':inputValue})
     return render(request,'pages/view_bookings.html',{'records':records})

def view_photos(request,id):
     room_view=get_object_or_404(rooms,id=id)

     return render(request,'pages/view_sayaw_rooms.html',{'room_view':room_view})

def view_sayaw_cottage(request,id):
     cottage=get_object_or_404(cottages,id=id)
     return render(request,'pages/view_sayaw_cottage.html',{'cottage':cottage})


    

def room_booking_view(request,id):
     cottage=cottages.objects.all()
     current_date = timezone.now()
     room=get_object_or_404(rooms,id=id)
     return render(request,'pages/reservation_form.html',{'room':room,'cottages':cottage})



    
def cottage_booking_view(request,id):
     room=rooms.objects.all()
     cottage=get_object_or_404(cottages,id=id)  
     return render(request,'pages/cottage_reservationform.html',{'cottage':cottage,'rooms':room})


def cottage_booking_process(request):
       room_price = 0
       error_msg=""
       success_msg="Thank you for visting sayaw resort"
       current_date = timezone.now()
       date_Reserved = current_date.strftime("%Y-%m-%d")
       current_time = timezone.localtime(timezone.now()).time()
       time_Reserved = current_time.strftime('%H:%M:%S')
       entrance_Fee=40
     
       if request.method=='POST':
       
         length=6
         characters = string.ascii_letters + string.digits
         transaction_code=''.join(random.choice(characters) for i in range(length))
        
         firstName=request.POST.get('firstname').capitalize()
         lastName=request.POST.get('lastname').capitalize()
         address=request.POST.get('address').capitalize()
         guest_No=request.POST.get('guest_no')
      
         cottage_price=request.POST.get('cottage_price')
         room=request.POST.get('room')
         cottage=request.POST.get('cottage')
         gate_No=request.POST.get('gate_no')
         date_In=request.POST.get('date_in')
         date_Out=request.POST.get('date_out')
         duration=request.POST.get('duration')
         time_In=request.POST.get('time_in')
         time_Out=request.POST.get('time_out')
         payment_method=request.POST.get('payment_method')
         cottage_price=int(cottage_price)


        # Get form data and capitalize names and address
    
        
         if cottage != '':
             cottage=int(cottage)
             reserve=get_object_or_404(cottages, cottage_number=cottage)
             reserve.is_availlable=False
             reserve.save()
         else:
             pass

         if room == '':
             room=0
         else:
             room=int(room)
         if guest_No !='':
             guest_No=int(guest_No)
         else:
             guest_No=0
      

        
         if room == '10':
             if guest_No > 10 and guest_No < 15:
                     room_price = 7000
             elif guest_No > 15 :
                  room_price = 10000
         else:       
             try:
                 room=int(room)
                 reserved=get_object_or_404(rooms,room_number=room)
                 room_price=reserved.room_price
                 reserved.is_availlable=False
                 reserved.save()
             except:
                     room_price=0
               
      
            
    
        
         if duration!=0 :
             cottage_price=int(cottage_price)*int(duration)
        

sayaw_app/templates/pages/chat.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat</title>
    <link rel="stylesheet" href="{% static 'css/chat2.css'%}">
</head>
<body>
   <form action="{% url "reservation_App:chat" %}" method="POST">
    {% csrf_token %}
<div class="main-div">
  <div class="response-div">


{% for result in response %}
<p>{{result.data}}</p>

{% endfor %}
  
  </div>


  <div class="user-div">
    
{% for msg  in convo %}

<p>{{msg.message}} <span style="margin-left:10%;">{% if status %}sent{% endif %}</span></p> 
{% endfor %}



  </div>


</div>
<div class="message">


    <input type="text" name="ask" placeholder="...."  style="border-radius:4px;border:0.60px solid gray;outline:none;">
    <input type="submit" value="send" name="Send">
</div>
</form>
</body>
</html>

sayaw_app/templates/pages/manage_Establishment.html

{% extends "dashboard.html" %}
{% load static %}

{% block title  %}||manage_establishment{% endblock  %}

{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/admin_dashboard36.css' %}">
    
</head>
<br><br><br><br><br>

<div class="button-div" >

    <form action="{% url "reservation_App:manage_establishment" %}" method="POST">
{% csrf_token %}
        <br><br>
    <input type="submit" name="establishment" value="Add room/cottage">
     <input type="submit" name="remove" value="Remove room/cottage">
     <input type="submit" name="update" value="Update Establishment">
     <input type="submit" name="add" value="Add Nationality">
     <input type="submit" name="data_load" value="Load Chatbot Data">
     <input type="submit" name="phone_number" value="Insert number">
     
     
    
    </form>

</div>
{% if chatbot_success %}
<center><h2>{{chatbot_success}}</h2></center>
{% endif %}



{% if remove %}
<form action="{% url "reservation_App:remove-services" %}" method="POST">
{% csrf_token %}


<label for="">Select option</label><br>
<select name="services" id="">
    <option value="">Select</option>
    <option value="room">Room</option>
    <option value="cottage">Cottage</option>
  
</select><br>
<label for="">Enter the number:</label>
<input type="number" name="number"><br><br>
<center><button type="submit" style="background-color:red;margin-left:10px;width:20%;padding:15px;">Delete</button></center>
</form>

{% elif phone_number %}

<center><form action="{% url "reservation_App:insert" %}" method="POST">
    {% csrf_token %}

    <label for="">Gcash number: </label> <input type="number" name="gcash"><br><br>
    <label for="">payMaya number: </label> <input type="number" name="paymaya">
    <center><button type="submit" style="width:30%; margin-left:0px; background-color:#333; " > Save </button></center>
</form></center>
{% elif add %}
<div style="width:100%;height:20vh;background-color:gainsboro;">
    <center><h2>Add new Nationality</h2></center>
    <center><form action="{% url "reservation_App:add-nationality" %}" method="POST">
        {% csrf_token %}
        <input type="text" name="nationality" style="font-size:17px;width:50%;" required><br><br>
       <center> <input style="width:50%;" type="submit" value="Add"></center>
    </form></center>
</div>

{% elif update %}
<center><h2>Update Establishment</h2></center><br><br>
<form action="{% url "reservation_App:update-services" %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <select name="services" id="">
        <option value="">Select option</option>
        <option value="room">Room</option>
        <option value="cottage">Cottage</option>
        <option value="table">Table</option>
    </select><br><br>
    <label for="">Enter number</label><br>
    <input type="number" name="number" placeholder="number"><br>
    <label for="">Gate number:</label><br>
    <input type="number" name="gate_number" placeholder=" New gate number"><br>
    <label for="">Price</label><br>
    <input type="number" placeholder=" New price" name="price"><br>
    <label for="">Image 1</label> <input style="background-color:whitesmoke;" type="file" name="image1" ><br><br>
    <label for="">Image 2</label> <input style="background-color:whitesmoke;" type="file" name="image2" ><br><br>
    <label for="">Image 3</label> <input style="background-color:whitesmoke;"  type="file" name="image3"><br><br>
    <label for="">Image 4</label> <input style="background-color:whitesmoke;" type="file" name="image4"><br><br>
    <label for="">Description:</label>
    <textarea name="description" id="" cols="30" rows="10" placeholder="Description"></textarea><br><br><br>
    <center><button type="submit" style="margin-left:10px;background-color:#006b7f;">Update</button></center>
</form>

{% elif data_load %}
<form action="{% url "reservation_App:data-loading" %}" method="POST">{% csrf_token %}
    <center><h1>Load Data</h1></center><br><br><br>
    <center><textarea name="data" id="" cols="30" rows="10"></textarea> </center><br><br>
   <center> <button type="submit" style="background-color:green; margin-left:0px;padding:13px;">LOAD</button></center>
</form>
{% elif establishment %}



    <div class="main-div" style="display:flex;justify-content:space-evenly;">

        <div class="room-div-property" style="width:50%;">
     
        <form action="{% url "reservation_App:add_room" %}" method="POST"   enctype="multipart/form-data">
            {% csrf_token %}
            <center><label for="">{{room_success_message}}</label></center>
           <center><h3>Add Room</h3></center>
                <label for="">Room Number:</label><br>
                <input type="number" name="room_number" required placeholder="Room Number"><br>
                <br>
                <select name="gate_number">
                    <option value="" required>Select gate number</option>
                    <option value="Gate 1">Gate 1</option>
                    <option value="Gate 2">Gate 2</option>
                </select><br>
                <label for="">Room Price:</label><br>
                <input type="number" name="room_price" placeholder="Room Price" required>
            <br>
                <div class="input-group">
                    <label for="file">Upload Image (PNG, JPG, JPEG):</label><br>
                    <label for="">Image 1</label>
                    <input type="file"  id="p1" name="p1"><br>
                    <label for="">Image 2</label>
                    <input type="file" id="p2" name="p2"  required><br>
                    <label for="">Image 3</label>
                    <input type="file" id="p3" name="p3"  required><br>
                    <label for="">Image 4</label>
                    <input type="file" id="p4" name="p4"  required><br>
                    <label for="">Description:</label>
                    <textarea name="description" id="" cols="30" rows="10" placeholder="Room Description"></textarea>
                </div>
                        <div class="btn-div">
                            <button type="submit" style="margin-left:0px;background-color:#6fa9b7;width:40%;" class="btn-submit">Add now</button>
                            <button type="button" class="btn-cancel" style="width:40%;">Cancel</button>
                        </div>
                        
        </form>
    </div>
    <div class="room-div-property" style="width:50%;" >
        <center><h3>Add Cottage</h3></center>
     
        <form action="{% url "reservation_App:add_cottage" %}" method="POST"   enctype="multipart/form-data">
            {% csrf_token %}
            <center><label for="">{{cottage_success_message}}</label></center>
          
                <label for="name">Cottage Number:</label>
                <input type="number" id="cottage_number" name="cottage_number" placeholder="Cottage Number" required>
                <br><br>
                <select name="gate_number">
                    <option value="" required>Select gate number</option>
                    <option value="Gate 1">Gate 1</option>
                    <option value="Gate 2">Gate 2</option>
                </select><br>
                <label for="">Cottage Price</label>
                <input type="number" name="cottage_price" id="cottage_price" placeholder="Cottage Price" required>
                <div class="input-group">
                    <label for="file">Upload Image (PNG, JPG, JPEG):</label><br>
                    <label for="">Image 1</label>
                    <input type="file" id="p1" name="p1"  required><br>
                    <label for="">Image 2</label>
                    <input type="file" id="p1" name="p2"  required><br>
                    <label for="">Image 3</label>
                    <input type="file" id="p1" name="p3"  required><br>
                    <label for="">Image 4</label>
                    <input type="file" id="p1" name="p4"  required><br>
                    <label for="">Description</label>
                    <textarea name="description" id="" cols="30" rows="10" placeholder="Cottage Description"></textarea>
                </div>
            
                    <div class="btn-div">
                        <button type="submit" style="margin-left:0px;background-color:#6fa9b7;width:40%;" class="btn-submit">Add now</button>
                        <button type="button" class="btn-cancel" style="width:40%;">Cancel</button>
                    </div>
        </form>
    </div>
   
    </div>
 
    {% endif %}
   {% if msg %}
    <center><h3>{{nationality}} <span>{{msg}}</span></h3></span></center>
    <center> <form action="{% url "reservation_App:refresher" %}" method="POST">
        {% csrf_token %}
     <button type="submit" style="background-color:lightblue;width:30%;margin-left:0px;border:1px solid green;">Okay</button><br><br>
    </form>
</center> 
{% elif remove_msg %}
<center><h3>{{nationality}} <span>{{msg}}</span></h3></span></center>
<center> <form action="{% url "reservation_App:refresher" %}" method="POST">
    {% csrf_token %}
    <center><h3>{{remove_msg}} <span>{{id}} remove from services</span></h3></center>
 <button type="submit" style="background-color:lightblue;width:30%;margin-left:0px;border:1px solid green;">Okay</button><br><br>
</form>
</center> 
{% elif room_success_message %}

<center><h3>{{room_success_message}}</h3></center><br>
<center> <form action="{% url "reservation_App:refresher" %}" method="POST">
    {% csrf_token %}
 <button type="submit" style="background-color:lightblue;width:30%;margin-left:0px;border:1px solid green;">Okay</button><br><br>
</form>
</center>
{% elif cottage_success_message %}

<center><h3>{{cottage_success_message}}</h3></center><br>
<center> <form action="{% url "reservation_App:refresher" %}" method="POST">
    {% csrf_token %}
 <button type="submit" style="background-color:lightblue;width:30%;margin-left:0px;border:1px solid green;">Okay</button><br><br>
</form>
</center>

{% elif room_update_msg %}
    <center><h3>{{room_update_msg}} <span>{{number}} updated successfully</span></h3></center>
    <center> <form action="{% url "reservation_App:refresher" %}" method="POST">
        {% csrf_token %}
     <button type="submit" style="background-color:lightblue;width:30%;margin-left:0px;border:1px solid green;">Okay</button><br><br>
    </form>
</center>
{% elif cottage_update_msg %}
<center><h3>{{cottage_update_msg}} <span>{{number}} updated successfully</span></h3></center><br>
<center> <form action="{% url "reservation_App:refresher" %}" method="POST">
    {% csrf_token %}
 <button type="submit" style="background-color:lightblue;width:30%;margin-left:0px;border:1px solid green;">Okay</button><br><br>
</form>
</center>
{% elif suc %}
<center><label for="">{{suc}}</label></center>
{% elif table_update_msg %}
<center><h3>{{table_update_msg}} <span>{{number}} updated successfully</span></h3></center><br>
<center> <form action="{% url "reservation_App:refresher" %}" method="POST">
    {% csrf_token %}
 <button type="submit" style="background-color:lightblue;width:30%;margin-left:0px;border:1px solid green;">Okay</button><br><br>
</form>
</center>
    {% endif %}
  
{% endblock  %}

sayaw_app/templates/pages/view_bookings.html
{% extends "dashboard.html" %}
{% load static %}




<head>
    <!-- Add Bootstrap CSS link -->
    
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<!-- Add Bootstrap JavaScript and Popper.js (if needed) -->

<link rel="stylesheet" href="{% static 'css/admin_dashboard36.css' %}">
</head>
{% block title %}||View Records{% endblock  %}

{% block view_records %}
<form action="{% url "reservation_App:view_bookings" %}" method="GET">
    <input type="search" value="{{input}}" placeholder="Search  lastname..." name="input_value">
   </form>

<table class="booking-table">
   
    <thead>
     <th style="text-align:center;">Guest ID</th>
     <th style="text-align:center;">Guest Name</th>
     <th style="text-align:center;">Guest Lastname</th>
     <th style="text-align:center;">Guest Address</th>
    <th style="text-align:center;">Guest No.</th>
     <th style="text-align:center;">Room No.</th>
     <th style="text-align:center;">Action</th>
     <th style="text-align:center;">View record</th>
 </thead>
 
    
 <tbody>


    {% if records %}
    {% for record in records %}
   <br><br><br><br><br><br>
    <tr> 
        <td class="{% cycle 'odd' 'even' %}" >{{record.id}}</td> 
        <td class="{% cycle 'odd' 'even' %}" >{{record.guest_Name}}</td>
        <td class="{% cycle 'odd' 'even' %}" >{{record.guest_Lastname}}</td>
        <td class="{% cycle 'odd' 'even' %}" >{{record.guest_Address}}</td>
        <td class="{% cycle 'odd' 'even' %}" >{{record.guest_Number}}</td>
        <td class="{% cycle 'odd' 'even' %}" >{{record.room_number}}</td>
        <td  ><a class="edit" href="{% url "reservation_App:update_view" record.pk %}">Edit</a><a class="delete" href="{% url "reservation_App:delete_record" record.id %}">Delete</a></td>
        <td  ><a  class="view" href="{% url "reservation_App:view_records" record.id %}">View</a></td>

    </tr>

    {% endfor %}

    {% elif query %}

    {% for record  in query %}
    <tr> 
        <td class="{% cycle 'odd' 'even' %}" >{{record.id}}</td> 
        <td class="{% cycle 'odd' 'even' %}" >{{record.guest_Name}}</td>
        <td class="{% cycle 'odd' 'even' %}" >{{record.guest_Lastname}}</td>
        <td class="{% cycle 'odd' 'even' %}" >{{record.guest_Address}}</td>
        <td class="{% cycle 'odd' 'even' %}" >{{record.guest_Number}}</td>
        <td class="{% cycle 'odd' 'even' %}" >{{record.room_number}}</td>
        <td class="{% cycle 'odd' 'even' %}" ><a class="edit" href="{% url "reservation_App:update_view" record.pk %}">Edit</a><a class="delete" href="{% url "reservation_App:delete_record" record.id %}">Delete</a></td>
        <td class="{% cycle 'odd' 'even' %}" ><a class="view" href="{% url "reservation_App:view_records" record.id %}">View</a></td>

    </tr>
    
    {% endfor %}
    {% else %}
    <tr>
       <center><td style="color:red;">No records found</td></center>
    </tr>
    {% endif %}
</tbody>
{% endblock  %}